export const LOGIN = "LOGIN"
export const REGISTER = "REGISTER"
export const GET_AUTH_USER = "GET_AUTH_USER"
export const LOGOUT = "LOGOUT"
export const GET_PRODUCTS = "GET_PRODUCTS"
export const SET_USER_IMAGE = "SET_USER_IMAGE"
export const GET_PRODUCTS_ByID = "GET_PRODUCTS_ByID"